import pygame
from CollisionGrid import CollisionGrid
from typing import Optional
from Monkey import *

class Player:
    def __init__(self, side):
        self.side = side
        self.monkey_map = {
            "monkey_0": "dart_monkey",
            "monkey_1": "dart_monkey",
            "monkey_2": "dart_monkey",
            "monkey_3": "dart_monkey"
        }
        self.money = 0
        self.income = 0
        self.bloons_queue = []
        self.last_send = 0
        self.bloons_list = pygame.sprite.Group()
        self.monkeys_list = pygame.sprite.Group()
        self.grid = CollisionGrid()

        self.selected_tower: Optional[str] = None
        self.active_monkey: Optional[Monkey] = None

    def check_hit(self, current_time, dt):
        # Use the player's own grid and own bloon list
        self.grid.clear()
        for b in self.bloons_list:
            b.move(dt)
            self.grid.insert_bloon(b)

        for m in self.monkeys_list:
            m.check_shoot(current_time, self.bloons_list)
            # Add the money generated by this monkey's projectiles this frame
            self.money += m.move_projectiles(dt, self.grid)